### ISSUE TITLE
WEBrick::HTTPServer going to shutdown. Hot reload

### ISSUE THREAD

**Issue by l7rf1i82** [eclipse/ceylon-lang.org#528]
Hello. What i need fix for serve the site locally with hot reload?

environment:
```
Linux ubuntu-focal 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
rvm 1.29.12
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-linux]
rake, version 10.1.0
Bundler version 1.17.3
```

after run:
```
$ rake -t
```
i have that out:
```
Generating: /vagrant/ceylon-lang.org/_site/stylesheets/themes/paraiso-dark.css
Generating: /vagrant/ceylon-lang.org/_site/xsd/overrides
***************************************************************************
Starting preview server at http://localhost:4242 (Press Ctrl-C to shutdown)
***************************************************************************
rake aborted!
ERROR: Running Awestruct failed.
/vagrant/ceylon-lang.org/Rakefile:133:in `run_awestruct'
/vagrant/ceylon-lang.org/Rakefile:61:in `block in <top (required)>'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/task.rb:236:in `call'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/task.rb:236:in `block in execute'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/task.rb:231:in `each'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/task.rb:231:in `execute'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/task.rb:168:in `invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/task.rb:197:in `block in invoke_prerequisites'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/task.rb:195:in `each'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/task.rb:195:in `invoke_prerequisites'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/task.rb:174:in `block in invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/task.rb:168:in `invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/task.rb:161:in `invoke'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/application.rb:153:in `invoke_task'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/application.rb:106:in `each'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/application.rb:106:in `block in top_level'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/application.rb:115:in `run_with_threads'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/application.rb:100:in `top_level'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/application.rb:78:in `block in run'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/application.rb:169:in `standard_exception_handling'
/usr/share/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rake/application.rb:75:in `run'
/usr/share/rvm/rubies/ruby-2.1.10/bin/rake:33:in `<main>'
Tasks: TOP => default => preview
```
if i run:
```
$ rake
```
i have that out:
```
Generating: /vagrant/ceylon-lang.org/_site/xsd/overrides
***************************************************************************
Starting preview server at http://localhost:4242 (Press Ctrl-C to shutdown)
***************************************************************************
[2021-09-29 07:18:16] INFO  WEBrick 1.3.1
[2021-09-29 07:18:16] INFO  ruby 2.1.10 (2016-04-01) [x86_64-linux]
[2021-09-29 07:18:16] INFO  WEBrick::HTTPServer#start: pid=8151 port=4242
[2021-09-29 07:18:16] INFO  going to shutdown ...
[2021-09-29 07:18:16] INFO  WEBrick::HTTPServer#start done.
rake aborted!
ERROR: Running Awestruct failed.
/vagrant/ceylon-lang.org/Rakefile:133:in `run_awestruct'
/vagrant/ceylon-lang.org/Rakefile:61:in `block in <top (required)>'
Tasks: TOP => default => preview
(See full trace by running task with --trace)
```
if i run:
```
$ ./webrick
```
webrick:
```ruby
#!/usr/bin/env ruby

require 'webrick'

root = File.expand_path '/vagrant/ceylon-lang.org/_site'
server = WEBrick::HTTPServer.new :Port => 4242, :DocumentRoot => root

trap 'INT' do server.shutdown end

server.start
```
i have that out:
```
[2021-09-29 08:00:54] INFO  WEBrick 1.3.1
[2021-09-29 08:00:54] INFO  ruby 2.1.10 (2016-04-01) [x86_64-linux]
[2021-09-29 08:00:54] INFO  WEBrick::HTTPServer#start: pid=10370 port=4242
```
and server work correctly

i want have hot reload for fast view my changes.

**Comment by l7rf1i82** [comment]
i fix this using next changes:

- delete `Gemfile.lock`
- install `ruby 2.4.10` via [rvm](https://rvm.io/)
- add change in `/Gemfile`
- add change in `/_ext/pipeline.rb`

#### /Gemfile:
```ruby
# use 0.6.1 version instead 0.5.5
gem 'awestruct', '>= 0.6.1'
# add this for fix message from cli out
gem 'htmlcompressor', '>= 0.0.3'
gem 'uglifier', '>= 1.3.0'
```
#### /_ext/pipeline.rb:
```ruby
# add this before Awestruct::Extensions::Pipeline.new do
require 'compass'
```

then install gems and start server:
```
rake clean[all]
rm -fR .bundle _tmp _bin
rake setup
rake check
rake preview
```
